/* ═══════════════════════════════════════════════════════════
   Calcutta Auction — Odds Loader
   Reads pre-computed win probabilities from BundledData
   (generated by scripts/bundle_data.py from the output of
   scripts/calculate_odds.py).  No fetch() required.
   ═══════════════════════════════════════════════════════════ */

const OddsLoader = (() => {
  'use strict';

  /**
   * Return pre-computed odds for a division (synchronous).
   * Kept as async to preserve existing call-sites.
   * @param {string} division - 'mens' or 'womens'
   * @returns {Promise<Object[]|null>}
   */
  async function loadOdds(division) {
    const data = BundledData.odds[division] || null;
    if (!data) console.warn(`No bundled odds for division "${division}"`);
    return data;
  }

  /** Load odds for the active division. */
  async function loadCurrentOdds() {
    return loadOdds(CalcuttaData.activeDivision);
  }

  /** No-op — kept for API compat with reload button. */
  function clearCache() { /* nothing to clear */ }

  /**
   * Match pre-computed odds to the current team list.
   * Teams without pre-computed odds get zeros.
   */
  function mapToTeams(precomputed, teams) {
    if (!precomputed || !teams) return [];
    const oddsMap = new Map(precomputed.map(o => [o.teamId, o]));
    return teams.map(t => {
      const o = oddsMap.get(t.id);
      return {
        teamId: t.id,
        teamName: t.name,
        A: o ? o.A : 0,
        B: o ? o.B : 0,
        C: o ? o.C : 0,
        D: o ? o.D : 0,
        any: o ? o.any : 0,
      };
    });
  }

  return { loadOdds, loadCurrentOdds, clearCache, mapToTeams };
})();
