/* ═══════════════════════════════════════════════════════════
   Calcutta Auction — Odds Loader
   Loads pre-computed win probabilities from JSON files
   generated by scripts/calculate_odds.py.

   The Monte Carlo simulation now runs in Python before
   deployment. This module simply fetches and caches the
   resulting JSON.
   ═══════════════════════════════════════════════════════════ */

const OddsLoader = (() => {
  'use strict';

  let _cache = { mens: null, womens: null };

  /**
   * Fetch pre-computed odds for a division.
   * @param {string} division - 'mens' or 'womens'
   * @returns {Promise<Object[]|null>}
   */
  async function loadOdds(division) {
    if (_cache[division]) return _cache[division];

    const url = `data/odds_${division}.json`;
    try {
      const resp = await fetch(url);
      if (!resp.ok) {
        console.warn(`Odds file not found: ${url} (${resp.status})`);
        return null;
      }
      const data = await resp.json();
      _cache[division] = data;
      return data;
    } catch (e) {
      console.warn(`Failed to load odds from ${url}:`, e);
      return null;
    }
  }

  /** Load odds for the active division. */
  async function loadCurrentOdds() {
    return loadOdds(CalcuttaData.activeDivision);
  }

  /** Invalidate cache (after re-running Python script). */
  function clearCache() {
    _cache = { mens: null, womens: null };
  }

  /**
   * Match pre-computed odds to the current team list.
   * Teams without pre-computed odds get zeros.
   */
  function mapToTeams(precomputed, teams) {
    if (!precomputed || !teams) return [];
    const oddsMap = new Map(precomputed.map(o => [o.teamId, o]));
    return teams.map(t => {
      const o = oddsMap.get(t.id);
      return {
        teamId: t.id,
        teamName: t.name,
        A: o ? o.A : 0,
        B: o ? o.B : 0,
        C: o ? o.C : 0,
        D: o ? o.D : 0,
        any: o ? o.any : 0,
      };
    });
  }

  return { loadOdds, loadCurrentOdds, clearCache, mapToTeams };
})();
